version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
    - "3535:3535"
    volumes:
    - .:/usr/NgCashApp
    depends_on:
      - db
    environment:
      - DB_NAME = ngcash
      - DB_PASS = 123456
      - DB_USER = admin
    networks:
      - my-network
    links:
      - db
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: